### PR TITLE
Minor fixes for MXE packaging

### PR DESCRIPTION
**Pull request by tonytheodore**

### CODE REVIEW

**Comment by tonytheodore** [comment]
Changed to WIP, it doesn't install the import lib and the Travis tests are failing (I may not be able to run these in a cross-compile)

**Comment by tonytheodore** [comment]
Removed WIP, the import lib is now installed correctly and the only new Travis failure compared to https://travis-ci.org/vanrein/quick-der/builds/296850957 is the first one:
```
 1/45 Test  #1: python_test ......................***Failed    0.22 sec
```

**Comment by tonytheodore** [comment]
Removed the `relax asn1ate and pytest-runner requirements` and test results are now the same as last pushed commit - I'll keep these changes locally.

```diff
commit 1d5e21fc369855c7d55c16b441e4df76272f0e46
Author: Tony Theodore <tonyt@logyst.com>
Date:   Mon Nov 6 23:00:31 2017 +1100

    python setup: relax asn1ate and pytest-runner requirements

diff --git a/setup.py b/setup.py
index d772f68..f15368c 100644
--- a/setup.py
+++ b/setup.py
@@ -31,12 +31,11 @@ setup(
     },
     install_requires=[
         'six',
-        'asn1ate==0.5.1.dev0',
+        'asn1ate>=0.5.1.dev0',
     ],
     dependency_links=[
         'git+https://github.com/kimgr/asn1ate.git@baf6a89b2f08892f184cf36c4c7a250251b195b1#egg=asn1ate-0.5.1.dev0',
     ],
-    setup_requires=['pytest-runner'],
-    tests_require=['pytest'],
+    tests_require=['pytest','pytest-runner'],
     test_suite='tests',
 )
```

**Comment by adriaandegroot** [comment]
What is this trying to achieve, and why? Just throwing in COMPONENTS markers doesn't make sense to me; there's probably a philosophy behind that, but I don't know which.

(relaxing the asn1ate version requirement, though, seems like a good idea)

**Comment by tonytheodore** [comment]
It's trying to provide more control over the installation:
  - separate static/shared libs and use standard `DESTINATIONS`
  - always install headers and config files
  - don't install docs

Using components has no impact on anyone using `make install` so existing build scripts won't be affected.

It's probably better to do this as build options leaving the current defaults - I'll do another PR for that.

**Pull request closed without merging**
