### PR TITLE
Simplify Python setup, use latest asn1ate

### PR DESCRIPTION
**Pull request by gijzelaerr**
This:
 * Centralises the Python installation
 * For now install asn1ate from github using a commit ID of a prerelease that should works for us 
 * Removes the setup.py generation from cmake
 * Move the scripts from `tool` to `python/`
 * Install the scripts using `setup.py`

Advantages:
 * Can install python code without CMake
 * No asn1ate code diplication in repo

Disadvantage:
 * Manual maintenance of version number in setup.py, could potentially be automated.

Todo:
 * modification of CMake logic to work with this

### CODE REVIEW

**Comment by vanrein** [comment]
Thanks, Gijs!

Could you please "git rebase -i" them together, and write a log summary [line] that explains what you've done to people reading the Quick DER log?  FWIW, you can then "git push --force" to override the history in the PR to your one new commit.  The current descriptions seem to make sense only within the context of this branch.

**Comment by gijzelaerr** [comment]
you can merge commits on github.

**Comment by gijzelaerr** [comment]
screen shot 2017-11-02 at 13 52 42

**Comment by vanrein** [comment]
Thanks, da's nieuw voor me!

**Pull request merged**
